services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://52.159.145.100:3306/chess
      DB_USER: chess_admin
      DB_PASS: ChessAdmin1234!

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
